using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace SpaceGameProj
{
    public class Matic
    {
        public void IntroCinematic()
        {
            {
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("                                       ╔════════════════════════════════════╗");
                WriteText.WriteLine("                                       ║                                    ║");
                WriteText.WriteLine("                                       ║        It's the year 28XX...       ║");
                WriteText.WriteLine("                                       ║                                    ║");
                WriteText.WriteLine("                                       ╚════════════════════════════════════╝");
                Thread.Sleep(3000);
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("                                       ╔════════════════════════════════════╗");
                WriteText.WriteLine("                                       ║   You are 34 years old, and your   ║");
                WriteText.WriteLine("                                       ║  parents have decided to kick you  ║");
                WriteText.WriteLine("                                       ║         out of the house....       ║");
                WriteText.WriteLine("                                       ╚════════════════════════════════════╝");
                Thread.Sleep(5000);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("                                       ╔════════════════════════════════════╗");
                WriteText.WriteLine("                                       ║  as you packed up your belongings  ║");
                WriteText.WriteLine("                                       ║   you realized maybe its time to   ║");
                WriteText.WriteLine("                                       ║      make a name for yourself...   ║");
                WriteText.WriteLine("                                       ╚════════════════════════════════════╝");
                Thread.Sleep(5000);
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("                                       ╔════════════════════════════════════╗");
                WriteText.WriteLine("                                       ║  Like a good child, you decide to  ║");
                WriteText.WriteLine("                                       ║    join a group of interstellar    ║");
                WriteText.WriteLine("                                       ║    traders who specialize in...    ║");
                WriteText.WriteLine("                                       ╚════════════════════════════════════╝");
                Thread.Sleep(5000);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("                                       ╔════════════════════════════════════╗");
                WriteText.WriteLine("                                       ║                                    ║");
                WriteText.WriteLine("                                       ║          illegal goods!!!          ║");
                WriteText.WriteLine("                                       ║                                    ║");
                WriteText.WriteLine("                                       ╚════════════════════════════════════╝");
                Thread.Sleep(5000);
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("                                       ╔════════════════════════════════════╗");
                WriteText.WriteLine("                                       ║     This is a cuthrought job,      ║");
                WriteText.WriteLine("                                       ║  full of danger after every turn,  ║");
                WriteText.WriteLine("                                       ║     but you must find a way...     ║");
                WriteText.WriteLine("                                       ╚════════════════════════════════════╝");
                Thread.Sleep(5000);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("                                       ╔════════════════════════════════════╗");
                WriteText.WriteLine("                                       ║     To buy and sell goods for      ║");
                WriteText.WriteLine("                                       ║   a profit, while dealing with     ║");
                WriteText.WriteLine("                                       ║the hazards this system has to offer║");
                WriteText.WriteLine("                                       ╚════════════════════════════════════╝");
                Thread.Sleep(5000);
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("                                       ╔════════════════════════════════════╗");
                WriteText.WriteLine("                                       ║        Will you survive?           ║");
                WriteText.WriteLine("                                       ║                                    ║");
                WriteText.WriteLine("                                       ║  Or perish in the dead of space?   ║");
                WriteText.WriteLine("                                       ╚════════════════════════════════════╝");
                Thread.Sleep(3000);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                WriteText.WriteLine("        ███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ╚██████╔╝╚██████╔╝   ██║   ███████║    ███████║██║  ██╗   ██║    ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                WriteText.WriteLine("        ███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ╚██████╔╝╚██████╔╝   ██║   ███████║    ███████║██║  ██╗   ██║    ");
                WriteText.WriteLine("        ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝     ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝    ╚══════╝╚═╝  ╚═╝   ╚═╝    ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                WriteText.WriteLine("        ███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ╚██████╔╝╚██████╔╝   ██║   ███████║    ███████║██║  ██╗   ██║    ");
                WriteText.WriteLine("        ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝     ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝    ╚══════╝╚═╝  ╚═╝   ╚═╝    ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                WriteText.WriteLine("        ███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ╚██████╔╝╚██████╔╝   ██║   ███████║    ███████║██║  ██╗   ██║    ");
                WriteText.WriteLine("        ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝     ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝    ╚══════╝╚═╝  ╚═╝   ╚═╝    ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                WriteText.WriteLine("        ███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ╚██████╔╝╚██████╔╝   ██║   ███████║    ███████║██║  ██╗   ██║    ");
                WriteText.WriteLine("        ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝     ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝    ╚══════╝╚═╝  ╚═╝   ╚═╝    ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                WriteText.WriteLine("        ███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ╚██████╔╝╚██████╔╝   ██║   ███████║    ███████║██║  ██╗   ██║    ");
                WriteText.WriteLine("        ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝     ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝    ╚══════╝╚═╝  ╚═╝   ╚═╝    ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                WriteText.WriteLine("        ███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ╚██████╔╝╚██████╔╝   ██║   ███████║    ███████║██║  ██╗   ██║    ");
                WriteText.WriteLine("        ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝     ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝    ╚══════╝╚═╝  ╚═╝   ╚═╝    ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                WriteText.WriteLine("        ███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ╚██████╔╝╚██████╔╝   ██║   ███████║    ███████║██║  ██╗   ██║    ");
                WriteText.WriteLine("        ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝     ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝    ╚══════╝╚═╝  ╚═╝   ╚═╝    ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                WriteText.WriteLine("        ███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ╚██████╔╝╚██████╔╝   ██║   ███████║    ███████║██║  ██╗   ██║    ");
                WriteText.WriteLine("        ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝     ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝    ╚══════╝╚═╝  ╚═╝   ╚═╝    ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                WriteText.WriteLine("        ███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ╚██████╔╝╚██████╔╝   ██║   ███████║    ███████║██║  ██╗   ██║    ");
                WriteText.WriteLine("        ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝     ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝    ╚══════╝╚═╝  ╚═╝   ╚═╝    ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                WriteText.WriteLine("        ███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ╚██████╔╝╚██████╔╝   ██║   ███████║    ███████║██║  ██╗   ██║    ");
                WriteText.WriteLine("        ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝     ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝    ╚══════╝╚═╝  ╚═╝   ╚═╝    ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                WriteText.WriteLine("        ███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ╚██████╔╝╚██████╔╝   ██║   ███████║    ███████║██║  ██╗   ██║    ");
                WriteText.WriteLine("        ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝     ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝    ╚══════╝╚═╝  ╚═╝   ╚═╝    ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                WriteText.WriteLine("        ███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ╚██████╔╝╚██████╔╝   ██║   ███████║    ███████║██║  ██╗   ██║    ");
                WriteText.WriteLine("        ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝     ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝    ╚══════╝╚═╝  ╚═╝   ╚═╝    ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                WriteText.WriteLine("        ███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ╚██████╔╝╚██████╔╝   ██║   ███████║    ███████║██║  ██╗   ██║    ");
                WriteText.WriteLine("        ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝     ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝    ╚══════╝╚═╝  ╚═╝   ╚═╝    ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                WriteText.WriteLine("        ███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ╚██████╔╝╚██████╔╝   ██║   ███████║    ███████║██║  ██╗   ██║    ");
                WriteText.WriteLine("        ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝     ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝    ╚══════╝╚═╝  ╚═╝   ╚═╝    ");
                Thread.Sleep(100);
                Console.Clear();
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("");
                WriteText.WriteLine("        ███████╗ ██████╗ ███╗   ███╗███████╗     ██████╗ ██╗   ██╗██╗   ██╗███████╗    ███████╗██╗  ██╗██╗   ██╗");
                WriteText.WriteLine("        ██╔════╝██╔═══██╗████╗ ████║██╔════╝    ██╔════╝ ██║   ██║╚██╗ ██╔╝██╔════╝    ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ");
                WriteText.WriteLine("        ███████╗██║   ██║██╔████╔██║█████╗      ██║  ███╗██║   ██║ ╚████╔╝ ███████╗    ███████╗█████╔╝  ╚████╔╝  ");
                WriteText.WriteLine("        ╚════██║██║   ██║██║╚██╔╝██║██╔══╝      ██║   ██║██║   ██║  ╚██╔╝  ╚════██║    ╚════██║██╔═██╗   ╚██╔╝   ");
                WriteText.WriteLine("        ███████║╚██████╔╝██║ ╚═╝ ██║███████╗    ╚██████╔╝╚██████╔╝   ██║   ███████║    ███████║██║  ██╗   ██║    ");
                WriteText.WriteLine("        ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝     ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝    ╚══════╝╚═╝  ╚═╝   ╚═╝    ");
                WriteText.WriteLine("                                         By Alex Mancino and Zach Herrera");
                WriteText.WriteLine("");
                WriteText.WriteLine("                                       ╔════════════════════════════════════╗");
                WriteText.WriteLine("                                       ║       Press any key to begin       ║");
                WriteText.WriteLine("                                       ╚════════════════════════════════════╝");
                Console.ReadLine();
            }
        }
    }
}
