// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickFix.Models;

namespace QuickFix.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190914184501_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuickFix.Models.Services", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BasePrice");

                    b.Property<DateTime>("CompletionDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsServiceDiscount");

                    b.Property<DateTime>("ServiceDate");

                    b.Property<string>("ServiceStatus");

                    b.Property<string>("ServiceType");

                    b.HasKey("Id");

                    b.ToTable("services");
                });
#pragma warning restore 612, 618
        }
    }
}
